### ISSUE TITLE
Kubernetes 1.22 support

### ISSUE THREAD

**Issue by roobre** [newrelic/nri-kubernetes#200]

**Comment by invidian** [comment]
So, to finish this, we miss:
- [ ] Release of https://github.com/newrelic/k8s-metadata-injection, to include https://github.com/newrelic/k8s-metadata-injection/commit/b95cb0137bdac1a6b92e8d81bcb976f6a5e47119.

Then optionally (as existing versions already support Kubernetes v1.22):
- [ ] Release of https://github.com/newrelic/newrelic-infra-operator to include https://github.com/newrelic/newrelic-infra-operator/pull/100.
- [ ] Release of https://github.com/newrelic/nri-kube-events to include https://github.com/newrelic/nri-kube-events/pull/66.

Charts PR: https://github.com/newrelic/helm-charts/pull/468

**Comment by gsanchezgavier** [comment]
I just released all integrations. Could you update the chart PR? Thanks!

**Comment by invidian** [comment]
>I just released all integrations. Could you update the chart PR? Thanks!

Thank you, done!
