### ISSUE TITLE
1.20/1.21 Support

### ISSUE THREAD

**Issue by roobre** [newrelic/nri-kubernetes#90]
Matrix for compat testing:

### Kubernetes versions:
- 1.20
- 1.21

### Projects:
- [ ] https://github.com/newrelic/nri-discovery-kubernetes
  - Expected: M. Should be easy but uses very dated client libraries (unversioned).
  - **Depends on nri-kubernetes**
  - PR: https://github.com/newrelic/nri-discovery-kubernetes/pull/30
- [x] https://github.com/newrelic/nri-kubernetes/
  - Expected: L. Integration is monolithic and complex, uses deprecated libraries and possibly endpoints.
  - PR: https://github.com/newrelic/nri-kubernetes/pull/111
- [x] https://github.com/newrelic/nri-kube-events/
  - Expected: S. Simple integration, already uses `0.20.x` client libraries.
  - PR: https://github.com/newrelic/nri-kube-events/pull/33
- [x] https://github.com/newrelic/nri-prometheus
  - Expected: XS, only uses "client" methods getting, listing, and subscribing to objects.
  - PR: https://github.com/newrelic/nri-prometheus/pull/179
- [x] https://github.com/newrelic/k8s-metadata-injection
  - Expected: M. It's just a webhook but uses very dated client libraries (unversioned).
  - PR: https://github.com/newrelic/k8s-metadata-injection/pull/93
